const E = { answer: 'A', guess: '' };
const B = { blank: 'yes' };

export const EXAMPLE_BOARD = [
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { blank: 'yes' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { blank: 'yes' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { blank: 'yes' }, { blank: 'yes' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { blank: 'yes' }, { blank: 'yes' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { blank: 'yes' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { blank: 'yes' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { blank: 'yes' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { blank: 'yes' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { blank: 'yes' }, { blank: 'yes' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }],
    [{ answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }, { answer: 'A', guess: '' }, { answer: 'N', guess: '' }, { answer: 'D', guess: '' }]
];

export const EXAMPLE_CLUES = {
    HORIZONTAL: [
        { clue: "h clue 1" },
        { clue: "h clue 2" },
        { clue: "h clue 3" },
        { clue: "h clue 4" },
        { clue: "h clue 5" },
        { clue: "h clue 6" },
        { clue: "h clue 7" },
        { clue: "h clue 9" },
        { clue: "h clue 10" },
        { clue: "h clue 11" },
        { clue: "h clue 12" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
        { clue: "h clue 13" },
    ],
    VERTICAL: [
        { clue: "v clue 1" },
        { clue: "v clue 2" },
        { clue: "v clue 3" },
        { clue: "v clue 4" },
        { clue: "v clue 5" },
        { clue: "v clue 6" },
        { clue: "v clue 7" },
        { clue: "v clue 8" },
        { clue: "v clue 9" },
        { clue: "v clue 10" },
        { clue: "v clue 11" },
        { clue: "v clue 12" },
        { clue: "v clue 12" },
        { clue: "v clue 12" },
        { clue: "v clue 12" },
        { clue: "v clue 12" },
        { clue: "v clue 12" },
        { clue: "v clue 12" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
        { clue: "v clue 13" },
    ]
}